global using System.ComponentModel.DataAnnotations;
global using System.ComponentModel.DataAnnotations.Schema;
global using Microsoft.EntityFrameworkCore;
global using CustomerMicroservice.Models;
global using CustomerMicroservice.Data;
global using CustomerMicroservice.DTO;
//global using CustomerMicroservice.Mapper;
global using CustomerMicroservice.Data.Repository;
global using CustomerMicroservice.Service;